version: '3.3'

services:
  mongo:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
    ports:
      - 27017:27017
    volumes:
      - D:\docker-volume\mongo:/data/db

  mongoe2e:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test123
    ports:
      - 27018:27017
    volumes:
      - D:\docker-volume\mongo-test:/data/db
